### ISSUE TITLE
Error in silva_blast

### ISSUE THREAD

**Issue by mjamy** [eukref/eukref#12]
Hi! 

I'm trying out this pipeline, but the `eukref_pipeline.py` script. 

Here is the error I am getting:

> Removing short sequences from initial fasta file
starting cycle 1
running blast
blasting against SILVA
Traceback (most recent call last):
  File "eukref_gbretrieve.py", line 450, in <module>
    'temp_results_500.fas', 'temp_results.silvatab')
  File "eukref_gbretrieve.py", line 203, in silva_blast
    if tax_d[ac_hit].count('Bacteria') > 0 or tax_d[
KeyError: 'KJ763345'

Just to add, I am using `usearch v7.0.1090`.

Any suggestions on how to fix this problem? Many thanks!

**Comment by kolecko007** [comment]
Hi,

Can you send me you input files and exact command. I will try to.rwproduce the error.

Best
Martin

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by mjamy** [comment]
Hi Martin, 

Thanks for your quick reply! I just emailed you the input file and command.

**Comment by mjamy** [comment]
Problem was resolved by downloading the latest version of `tax_d.bin` file instead of relying on the file included in `databases.tar.gz`.

Thanks Martin for the help :)
